### ISSUE TITLE
cron job doesn't update wallpaper XFCE

### ISSUE THREAD

**Issue by rarealphacat** [boramalper/himawaripy#105]
i can see it running every 10 mins under htop, so the cron is working but the wallpaper itself do not update.
*/10 * * * * /usr/bin/himawaripy

I thought it has something to do with the display so i changed the cron into this, but still no luck.
*/10 * * * * DISPLAY=:0.0 /usr/bin/himawaripy

But if i run this himawaripy command in the terminal myself it updates successfully, any ideas?

EDIT: Guess it does not support XFCE yet.

**Comment by bbbf0621** [comment]
It's solved by enabling random wallpapers under the cache folder, it wouldn't auto select new file name even if there's only 1 file exist.

**Comment by bbbf0621** [comment]
Sorry, turns out cron does not accept */10 as to run every 10 minutes

**Comment by rarealphacat** [comment]
Couldn't detect your desktop environment ('unknown'), but you have 'feh' installed so we will use it...
Edit: Finally got it running by putting himawarpi command inside conky lol, cron didn't work for me idk why.

**Comment by boramalper** [comment]
Fixed it in the new version. I would appreciate if you can give it a try and let me know!
