### ISSUE TITLE
Add a free license

### ISSUE THREAD

**Issue by pizzamaker** [boramalper/himawaripy#14]
This repo seems to lack license information. I suggest AGPLv3 :)

**Comment by PenguinPaul** [comment]
Well, since he based it on the powershell script he'll need to look at that license.

**Comment by boramalper** [comment]
> Well, since he based it on the powershell script he'll need to look at that license.

It's not based on that script, but it surely gave me the aspiration so I thought it deserves credit. :)

I'll ask the authors of the merged pull requests to see if they are okay with MIT License.

**Comment by boramalper** [comment]
Done!
