### ISSUE TITLE
xfce4 on linuxmint 17.3

### ISSUE THREAD

**Issue by ManuLinares** [boramalper/himawaripy#15]
It downloads fine, sets the "xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitor0/image-path"  but background doesn't change.

**Comment by boramalper** [comment]
Related to #4

**Comment by rbong** [comment]
Does the pull request fix your issue? If not...

Is there any output for the script? What is the output of

```
xfconf-query --channel xfce4-desktop --list | grep backdrop
```

**Comment by boramalper** [comment]
Closing the issue due to inactivity. Feel free to continue though, I'll open it again.
