### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Mearman** [boramalper/himawaripy#17]
Could you make it possible to just download the images or even better make it compatible with Windows and/or OSX?

**Comment by the4ndy** [comment]
Per the author via [this post](https://www.reddit.com/r/linux/comments/445gil/i_wrote_a_python_script_that_puts_a_nearrealtime/), they indicated that this script is based on a PowerShell script that can be found [here](https://www.reddit.com/r/programming/comments/441do9/i_made_a_windows_powershell_script_that_puts_a/)

**Comment by andrew867** [comment]
@MearWolf If you take out lines 55-69 you should be able to run it on OS X, the image will be saved as ~/.himawari/himawari-latest.png

**Comment by davidpelayo** [comment]
@andrew867 it doesn't. could you specify better how or create a PR for it?
UPDATE: We have [a PR](https://github.com/boramalper/himawaripy/pull/19) already created. And it's working.

**Comment by boramalper** [comment]
I'm waiting for authors' permission to license their contribution under MIT License, then I'll merge it as soon as possible.

For now, you can try this: https://github.com/boramalper/himawaripy/pull/13

**Comment by boramalper** [comment]
There is already a working [Windows version](https://www.reddit.com/r/programming/comments/441do9/i_made_a_windows_powershell_script_that_puts_a/) (and also Windows doesn't come with Python installed) so probably there will never be Windows version. OS X support is added though! :)
