### ISSUE TITLE
No Module named PIL

### ISSUE THREAD

**Issue by the4ndy** [boramalper/himawaripy#21]
My machine is an Xubuntu 14.04 box running Xfce4. I know it doesnt say its supported but I thought I would give it a try and report back, unfortunately I get caught on a python module. The error is below

```
Traceback (most recent call last):
  File "himawaripy.py", line 11, in <module>
    from PIL import Image
ImportError: No module named 'PIL'

```

Some research on the PIL import error told me that I should replace the line:
`from PIL import Image`
with
`import Image`

That gave the same error as above, expect the module names were obviously different. This is likely an issue of my own doing, but I am hoping someone can assist

**Comment by whbdupree** [comment]
You need to install the Python Image Library. On one of my Ubuntu machines, it is called python3-pil for python 3. So, you should try the following command:
sudo apt-get install python3-pil 
Then try himawaripy again.
EDIT: this should work for "from PIL import Image" so if you changed some things, you should use the original source

**Comment by boramalper** [comment]
Sorry for the confusion, I added instructions to README about how to install dependencies. https://github.com/boramalper/himawaripy/commit/d2c7f827706615e449b67eae548666f85a3c9390
