### ISSUE TITLE
Create a setup.py, runner script, etc

### ISSUE THREAD

**Issue by ghost** [boramalper/himawaripy#23]
Hi, 

Like I said on Reddit (https://www.reddit.com/r/linux/comments/445gil/i_wrote_a_python_script_that_puts_a_nearrealtime/cznyiuo), I had to write a setup.py and patch your application.

I do not do a pull request with this cause I'm not familiar with Python but I think this is a good point to have a well prepared application for packaging purpose.

The setup.py I wrote : [setup.py](https://aur.archlinux.org/cgit/aur.git/tree/setup.py?h=himawaripy-git)

The "start" script to run the application (/usr/bin/) : [start](https://aur.archlinux.org/cgit/aur.git/tree/start?h=himawaripy-git)

The patch I had to do when the application is installed with the previous setup.py :

```
sed -i 's/from utils/from himawaripy.utils/' himawaripy.
```

**Comment by wesbarnett** [comment]
I've put in a pull request for a different setup.py. There's no need to create a different start script. See #42

**Comment by ghost** [comment]
Ok, I'm not used to Python so I bet your dev is better no problem.

_edit : I closed my pull request_

**Comment by ghost** [comment]
Close since this pull request is merged : https://github.com/boramalper/himawaripy/pull/42
But I opened a new issue here : https://github.com/boramalper/himawaripy/issues/44
