### ISSUE TITLE
Don't work with GNOME 3

### ISSUE THREAD

**Issue by paulcarroty** [boramalper/himawaripy#27]
```
$ ./himawaripy.py 
Updating...
Latest version: 2016/02/05 16:00:00 GMT

Traceback (most recent call last):
  File "./himawaripy.py", line 91, in <module>
    main()
  File "./himawaripy.py", line 63, in main
    res = p.map(download_chunk, product(range(level), range(level), (latest,)))
  File "/usr/lib64/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f1d0a739f60>'. Reason: 'TypeError("cannot serialize '_io.BufferedReader' object",)'
```

Python 3.5, python3-pillow 3.1.0.

**Comment by ghost** [comment]
I don't think this is relatied to Gnome 3, because it worked well with my Gnome 3 and your error is triggered before the desktop environment calls.

This is the download line from the python script that trigger the error : 
 res = p.map(download_chunk, product(range(level), range(level), (latest,)))

**Comment by boramalper** [comment]
@Sutat You're right. The problem mentioned in issue #29 as well.

I have no idea about what may caused the problem, since we are just passing 2 integers and a `time.struct_time` object, and all of them are serializable.

**Comment by ubrikkean** [comment]
No idea if this helps, but the first time I had already set the size bigger in the config, and I got this error... then I moved it back to the default 550x550, and it worked. (Pantheon on Elementary OS 0.3.2)

EDIT: confirmed, it doesn't seem to work with any non-default resolution settings, tried a whole bunch of them :(

**Comment by solomondg** [comment]
That worked, thank you! Any idea how to get it to work at higher
resolutions?

**Comment by boramalper** [comment]
> No idea if this helps, but the first time I had already set the size bigger in the config, and I got this error...

Ah, I see. :) The variables `height` and `width` is the height and width of **one** tile. As you increase the level, more tiles will be downloaded and thus the resolution and the quality of the image will increase as well.
