### ISSUE TITLE
TypeError("cannot serialize '_io.BufferedReader' object",)

### ISSUE THREAD

**Issue by solomondg** [boramalper/himawaripy#29]
So, trying to run this (./himawaripy.py), it outputs the following:
`$user@$hostname:~/Downloads/himawaripy$ ./himawaripy.py 
Updating...
Latest version: 2016/02/05 18:00:00 GMT

Traceback (most recent call last):
  File "./himawaripy.py", line 91, in <module>
    main()
  File "./himawaripy.py", line 63, in main
    res = p.map(download_chunk, product(range(level), range(level), (latest,)))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f373e9737f0>'. Reason: 'TypeError("cannot serialize '_io.BufferedReader' object",)'`

This is on Debian Stretch, `/usr/bin/env python3 --version` returns `Python 3.5.1+`, pillow is installed, running XFCE4. Did I do something wrong, or is this a legitimate problem?

**Comment by gamerdonkey** [comment]
I got a very similar error when I changed the width or height variables under the configuration section of the script. Changing them both back to the default of 550 allowed the script to run.

**Comment by boramalper** [comment]
Sorry for the confusion: The variables `height` and `width` are the height and width of **one** tile. You shouldn't change those variables, but as you increase the level, more tiles will be downloaded and thus the resolution and the quality of the image will increase as well.

Now `height` and `width` variables are moved from Configuration to prevent further confusion.
