### ISSUE TITLE
LXDE

### ISSUE THREAD

**Issue by rbong** [boramalper/himawaripy#34]
The regular command does not work for me.

```
display -window root ~/.himawari/himawari-latest.png
```

It does not complain, but the background remains unchanged. I successfully changed my background with this command.

```
pcmanfm --set-wallpaper ~/.himawari/himawari-latest.png --wallpaper-mode=fit
```

I have already submitted pull request #33. It would be appreciated if someone could confirm the original command does not work and the new one does.

**Comment by boramalper** [comment]
Pull request merged. Thanks!
