### ISSUE TITLE
xfce4 on archlinux

### ISSUE THREAD

**Issue by whbdupree** [boramalper/himawaripy#4]
This is the output I get when I run it.  I am on arch, so 'python' is python3 (version included below).
$ python himawaripy.py 
Updating...
Latest version: 2016/02/04/16:20:00 GMT

Downloading tiles: 16/16 completed
Downloaded

Property "/backdrop/screen0/monitor0/image-path" does not exist on channel "xfce4-desktop". If a new property should be created, use the --create option.
Done!

$ python
Python 3.5.1 (default, Dec  7 2015, 12:58:09) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

**Comment by boramalper** [comment]
Can you please paste the output of the following command:

```
xfconf-query --channel xfce4-desktop --list
```

**Comment by whbdupree** [comment]
$ xfconf-query --channel xfce4-desktop --list
/backdrop/screen0/monitor0/workspace0/color-style
/backdrop/screen0/monitor0/workspace0/image-style
/backdrop/screen0/monitor0/workspace0/last-image
/backdrop/screen0/monitor0/workspace1/color-style
/backdrop/screen0/monitor0/workspace1/image-style
/backdrop/screen0/monitor0/workspace1/last-image
/backdrop/screen0/monitor0/workspace2/color-style
/backdrop/screen0/monitor0/workspace2/image-style
/backdrop/screen0/monitor0/workspace2/last-image
/backdrop/screen0/monitor0/workspace3/color-style
/backdrop/screen0/monitor0/workspace3/image-style
/backdrop/screen0/monitor0/workspace3/last-image
/backdrop/screen0/monitorHDMI-0/workspace0/color-style
/backdrop/screen0/monitorHDMI-0/workspace0/image-style
/backdrop/screen0/monitorHDMI-0/workspace0/last-image
/backdrop/screen0/monitorHDMI-0/workspace1/color-style
/backdrop/screen0/monitorHDMI-0/workspace1/image-style
/backdrop/screen0/monitorHDMI-0/workspace1/last-image
/backdrop/screen0/monitorHDMI-0/workspace2/color-style
/backdrop/screen0/monitorHDMI-0/workspace2/image-style
/backdrop/screen0/monitorHDMI-0/workspace2/last-image
/backdrop/screen0/monitorHDMI-0/workspace3/color-style
/backdrop/screen0/monitorHDMI-0/workspace3/image-style
/backdrop/screen0/monitorHDMI-0/workspace3/last-image
/desktop-icons/show-thumbnails
/desktop-icons/style
/last/window-height
/last/window-width

**Comment by ghost** [comment]
Erreur is reproduced here.
Latest Arch/Xfce

**Comment by boramalper** [comment]
So according to what I found on the Internet, there must be property

```
/backdrop/screenX/monitorX/image-path
```

that we can change to change the background. I don't know if are there any other way around to do this, and I can't try it myself, since I don't have XFCE installed.

I'd be glad if you can come up with a solution. :)

**Comment by rbong** [comment]
There is no longer an image-path property. Backgrounds are now set by changing the last-image property, as odd as that may seem. Needed to change

```
 /backdrop/screen0/monitor0/image-path
```

to

```
 /backdrop/screen0/monitor0/workspace0/last-image
```

**Comment by whbdupree** [comment]
rbong, that doesn't work for me.

$ python himawaripy.py 
Updating...
Latest version: 2016/02/05 19:50:00 GMT

Property "/backdrop/screen0/monitor0/last-image" does not exist on channel "xfce4-desktop". If a new property should be created, use the --create option.

Done!

**Comment by whbdupree** [comment]
OK, I see that you have added workspace0 to the path. When I try that, himawaripy.py runs cleanly. I get on error message, but my background doesn't change.

**Comment by rbong** [comment]
You also need to add /worspace0 after /monitor0

     /backdrop/screen0/monitor0/workspace0/last-image

**Comment by rbong** [comment]
What is the error message?

**Comment by whbdupree** [comment]
There is no error message, and my  background doesn't change.

$ python himawaripy.py 
Updating...
Latest version: 2016/02/05 19:50:00 GMT

Downloading tiles: 16/16 completed
Done!

**Comment by rbong** [comment]
Are you sure you're using monitor0, and not monitorHDMI-0? Also, are you on workspace0? The desired value should be somewhere in the command

```
xfconf-query --channel xfce4-desktop --list | grep last-image
```

**Comment by whbdupree** [comment]
I am apparently using monitorHDMI-0. It is working for me now!

**Comment by rbong** [comment]
That's great!
