### ISSUE TITLE
Multiple Monitors?

### ISSUE THREAD

**Issue by jcmiller11** [boramalper/himawaripy#40]
The original version of my OS X support branch just set the main monitor's desktop picture, @cj-zeiger  was kind enough to submit a pull request to me that sets all of them. Can anyone comment on how multiple monitors work with the other desktop environments like on Linux so we could perhaps put in a cross-platform, configurable, setting to allow the users to select exactly which monitors they want the script to set the desktop picture on?

**Comment by pbzeppelin** [comment]
In MATE:
By the default settings, all monitors have the same wallpaper. I think there's a way to set an idividual one per each monitor, but I haven't looked too far into it.

GNOME 3:

Same, I believe. Someone else will have to confirm this as I avoid GNOME whenever I can

XFCE:

Allows you to set different wallpapers per monitor per the settings menu, not sure if you can set it from the CLI. If that's possible, I imagine multi-monitor users would definitely like this ability. At the very least, there should be an option to just download and stitch, not set. That way, you could have XFCE point at the latest image and rotate it every 10 minutes or so.

**Comment by rbong** [comment]
You can indeed set different wallpapers per-monitor with xfce through cli. With the latest version of this script, multi monitors are supported by xfce, although it's nothing robust.

**Comment by jcmiller11** [comment]
I was hoping to use this issue for us to discuss a robust cross platform setting variable, perhaps a python list or something, that we can check when we get to where we set the actual desktop picture based on environment "does this DE support multiple monitors?  if so, which monitors should we set?"
