### ISSUE TITLE
Mac OS X Change Desktop Background

### ISSUE THREAD

**Issue by hdiwan** [boramalper/himawaripy#41]
Looks like you [can change the desktop background](http://stackoverflow.com/questions/431205/how-can-i-programatically-change-the-background-in-mac-os-x) pretty easily with the [appscript](https://pypi.python.org/pypi/appscript) plugin. I will [put code up shortly](http://www.prolificprogrammer.com) to change the background to NASA's latest picture of the day, modifying this to allow for the JSA Earth picture is straightforward and is left as an exercise to you guys.

**Comment by boramalper** [comment]
I'm not in favor of adding another dependency. Is current implementation not working for you?

**Comment by hdiwan** [comment]
No, it doesn't work under OS X. If you want to avoid a dependency, invoke osascript directly using subprocess or use pyobjc, included with the system since OS X 10.5

**Comment by boramalper** [comment]
>  invoke osascript directly using subprocess

That's exactly what we're doing: https://github.com/boramalper/himawaripy/blob/master/himawaripy.py#L85

I have no idea what causes it. A wild question, what is your OS X and osascript version?

**Comment by boramalper** [comment]
I'm closing the issue as there are no more answers for three days. Feel free to raise it again, if you need so.

**Comment by cezhunter** [comment]
I am having an issue with the mac os Implementation, it seems to go through the process of installation successfully: 
`sudo python3 setup.py install
running install
running bdist_egg
running egg_info
writing dependency_links to himawaripy.egg-info/dependency_links.txt
writing requirements to himawaripy.egg-info/requires.txt
writing himawaripy.egg-info/PKG-INFO
writing entry points to himawaripy.egg-info/entry_points.txt
writing top-level names to himawaripy.egg-info/top_level.txt
reading manifest file 'himawaripy.egg-info/SOURCES.txt'
writing manifest file 'himawaripy.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-intel/egg
running install_lib
running build_py
creating build/bdist.macosx-10.6-intel/egg
creating build/bdist.macosx-10.6-intel/egg/himawaripy
copying build/lib/himawaripy/__init__.py -> build/bdist.macosx-10.6-intel/egg/himawaripy
copying build/lib/himawaripy/config.py -> build/bdist.macosx-10.6-intel/egg/himawaripy
copying build/lib/himawaripy/himawaripy.py -> build/bdist.macosx-10.6-intel/egg/himawaripy
copying build/lib/himawaripy/utils.py -> build/bdist.macosx-10.6-intel/egg/himawaripy
byte-compiling build/bdist.macosx-10.6-intel/egg/himawaripy/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/himawaripy/config.py to config.cpython-36.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/himawaripy/himawaripy.py to himawaripy.cpython-36.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/himawaripy/utils.py to utils.cpython-36.pyc
creating build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying himawaripy.egg-info/PKG-INFO -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying himawaripy.egg-info/SOURCES.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying himawaripy.egg-info/dependency_links.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying himawaripy.egg-info/entry_points.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying himawaripy.egg-info/requires.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying himawaripy.egg-info/top_level.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/himawaripy-1.1-py3.6.egg' and adding 'build/bdist.macosx-10.6-intel/egg' to it
removing 'build/bdist.macosx-10.6-intel/egg' (and everything under it)
Processing himawaripy-1.1-py3.6.egg
Removing /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/himawaripy-1.1-py3.6.egg
Copying himawaripy-1.1-py3.6.egg to /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
himawaripy 1.1 is already the active version in easy-install.pth
Installing himawaripy script to /Library/Frameworks/Python.framework/Versions/3.6/bin

Installed /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/himawaripy-1.1-py3.6.egg
Processing dependencies for himawaripy==1.1
Searching for tzlocal==1.2.2
Best match: tzlocal 1.2.2
Processing tzlocal-1.2.2-py3.6.egg
tzlocal 1.2.2 is already the active version in easy-install.pth

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tzlocal-1.2.2-py3.6.egg
Searching for pytz==2016.6.1
Best match: pytz 2016.6.1
Processing pytz-2016.6.1-py3.6.egg
pytz 2016.6.1 is already the active version in easy-install.pth

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytz-2016.6.1-py3.6.egg
Searching for python-dateutil==2.5.3
Best match: python-dateutil 2.5.3
Processing python_dateutil-2.5.3-py3.6.egg
python-dateutil 2.5.3 is already the active version in easy-install.pth

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/python_dateutil-2.5.3-py3.6.egg
Searching for Pillow==3.3.0
Best match: Pillow 3.3.0
Processing Pillow-3.3.0-py3.6-macosx-10.6-intel.egg
Pillow 3.3.0 is already the active version in easy-install.pth
Installing thresholder.py script to /Library/Frameworks/Python.framework/Versions/3.6/bin
Installing pilfont.py script to /Library/Frameworks/Python.framework/Versions/3.6/bin
Installing pilprint.py script to /Library/Frameworks/Python.framework/Versions/3.6/bin
Installing pilconvert.py script to /Library/Frameworks/Python.framework/Versions/3.6/bin
Installing createfontdatachunk.py script to /Library/Frameworks/Python.framework/Versions/3.6/bin
Installing gifmaker.py script to /Library/Frameworks/Python.framework/Versions/3.6/bin
Installing pilfile.py script to /Library/Frameworks/Python.framework/Versions/3.6/bin
Installing pildriver.py script to /Library/Frameworks/Python.framework/Versions/3.6/bin
Installing explode.py script to /Library/Frameworks/Python.framework/Versions/3.6/bin
Installing viewer.py script to /Library/Frameworks/Python.framework/Versions/3.6/bin
Installing painter.py script to /Library/Frameworks/Python.framework/Versions/3.6/bin
Installing player.py script to /Library/Frameworks/Python.framework/Versions/3.6/bin
Installing enhancer.py script to /Library/Frameworks/Python.framework/Versions/3.6/bin

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Pillow-3.3.0-py3.6-macosx-10.6-intel.egg
Searching for appdirs==1.4.0
Best match: appdirs 1.4.0
Processing appdirs-1.4.0-py3.6.egg
appdirs 1.4.0 is already the active version in easy-install.pth

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/appdirs-1.4.0-py3.6.egg
Searching for six==1.10.0
Best match: six 1.10.0
Processing six-1.10.0-py3.6.egg
six 1.10.0 is already the active version in easy-install.pth

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six-1.10.0-py3.6.egg
Finished processing dependencies for himawaripy==1.1`

However, I can't find the executable (which -- himawaripy does not produce any results). 
Any help will be greatly appreciated, thank you.

**Comment by boramalper** [comment]
Hmm, I've never used a mac but let me try my best:

Try running: `/usr/local/bin/himawaripy` from your terminal. If it works, it works! Then follow [the instructions](https://github.com/boramalper/himawaripy#for-mac-osx-users).
