### ISSUE TITLE
Current setup.py install more than one script in /usr/bin

### ISSUE THREAD

**Issue by ghost** [boramalper/himawaripy#44]
Current AUR setup.py :
~/pkg/himawaripy-git   master ●  pacman -Ql himawaripy-git
himawaripy-git /usr/
himawaripy-git /usr/bin/
himawaripy-git /usr/bin/himawaripy

Current himawaripy github setup.py :
~/pkg/himawaripy-git   dev ●  pacman -Ql himawaripy-git
himawaripy-git /usr/
himawaripy-git /usr/bin/
himawaripy-git /usr/bin/himawaripy
himawaripy-git /usr/bin/himawaripy.py
himawaripy-git /usr/bin/utils.py

AUR setup.py had one entrypoint into /usr/bin.
I dislike the current implementation, and I think I'll keep the current AUR setup.py until this will be fixed or someone convince me not to.

AUR setup.py (not perfect, and use an other script, so not well written) : https://github.com/boramalper/himawaripy/pull/30

**Comment by boramalper** [comment]
I'll work on it. Also @wesbarnett might be interested in as well.

**Comment by boramalper** [comment]
It should be fine now.

**Comment by ghost** [comment]
This is fine on arch, package AUR up to date, I deleted my setup.py from the package to use yours.
