### ISSUE TITLE
Wrong instruccions for systemd

### ISSUE THREAD

**Issue by guillefar** [boramalper/himawaripy#47]
There is no instruccions for what have to go inside himawaripy.service, and also path is wrong (and no INSTALLATION_PATH to be replaced)

```
### Configure
    vi systemd/himawaripy.service
    # Replace "<INSTALLATION_PATH>" with the output of the aforementioned command.
```

**Comment by boramalper** [comment]
`<INSTALLATION_PATH>` is the output of the command `which -- himawaripy`.

**Comment by guillefar** [comment]
Yes, but there is no INSTALLATION_PATH here: 

 ### Configure
        vi systemd/himawaripy.service
        # Replace "<INSTALLATION_PATH>" with the output of the aforementioned command.

```
    ### Copy systemd configuration
    cp systemd/himawaripy.{service,timer} $HOME/.config/systemd/user/

    ### Enable and start the timer
    systemctl --user enable --now himawaripy.timer
```

And in no place says what the content of systemd/himawaripy.service should be.

**Comment by boramalper** [comment]
You need to replace the `<INSTALLATION_PATH>` in the file `systemd/himawaripy.service` with the output of the conmand `which -- himawaripy`.

I hope it's finally clear enough.
