### ISSUE TITLE
Option to disable offset

### ISSUE THREAD

**Issue by p4block** [boramalper/himawaripy#48]
I just want to get the latest available image, could it be possible to pass an option to the script so it ignores the offset? 

This instead of having to edit the config file

**Comment by boramalper** [comment]
I want to keep it simple, so I'm not planning to add runtime parameters for now.

May I learn the reason of needing runtime parameters instead of config file?

**Comment by p4block** [comment]
I respect the decision on simplicity, but runtime parameters are a must imho

Yesterday I found that I was getting an offset picture of the Earth instead of the realtime one, so I tried running the software with -h and --help, but nothing happened. Some info on usage is somewhat expected.

A quick locate found the configuration file buried very deep inside the filesystem, and I edited it. Everything works fine and realtime now. 

However, without runtime parameters support it is impossible to script the program in different ways. Two users can't have different configurations, a single user can't get different quality images on demand... who knows what use cases someone may find. 

I think it would be useful at most and simple convention following at least. 

However, the software works and it could be argued any fancy-anything is outside its scope. No problem with that, really. 

This piece of software is great anyhow :+1:

**Comment by boramalper** [comment]
> A quick locate found the configuration file buried very deep inside the filesystem
> 
> Two users can't have different configurations

I think the points you raised are fair enough, I'll try to add runtime parameters support.

Thanks for the suggestion! :)

**Comment by boramalper** [comment]
Done in [v2](https://github.com/boramalper/himawaripy/commit/a9fd7f538d1deaa36f1e4f443c0b86738819589a). :)

Many many thanks!
