### ISSUE TITLE
doesn't work on gnome3

### ISSUE THREAD

**Issue by mxmaher** [boramalper/himawaripy#5]
line 16 in utils.py: desktop_session = os.environ.get("DESKTOP_SESSION")
returns "unknown"

**Comment by boramalper** [comment]
Which distro are you using?

**Comment by mxmaher** [comment]
ubuntu 15.04
I've it fixed already see the pull requests
it's only a one line change

**Comment by boramalper** [comment]
Can you try again using the [latest commit](https://github.com/boramalper/himawaripy/commit/af7c49c2fb417c633d87278ac1deb9b336fc7cdf) please?

**Comment by mxmaher** [comment]
it works now
