### ISSUE TITLE
KDE 5 support

### ISSUE THREAD

**Issue by mamantoha** [boramalper/himawaripy#57]
You can set a wallpaper in Plasma 5.7 with this command:

```
qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops();print (allDesktops);for (i=0;i<allDesktops.length;i++) {d = allDesktops[i];d.wallpaperPlugin = "org.kde.image";d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");d.writeConfig("Image", "file:///path/to/image.png")}'
```

I hope this could help you to add support for KDE 5.

**Comment by boramalper** [comment]
Thanks a lot! Do you know how to detect KDE version programmatically, then I can implement it right away.

**EDIT:** I've just realized that it can't change the background in KDE 4 as well (see [`set_background()`](https://github.com/boramalper/himawaripy/blob/master/himawaripy/utils.py#L8))! Do you know how to change background in KDE 4.

**Comment by mamantoha** [comment]
@boramalper no, I don't use KDE 4.

Thanks @imnofox for implementation :beer:

**Comment by boramalper** [comment]
Done!
