### ISSUE TITLE
No Image

### ISSUE THREAD

**Issue by hche608** [boramalper/himawaripy#68]
I am using Mac OS 10.11.6, I got no image, how to solve the problem
![image](https://cloud.githubusercontent.com/assets/6982065/17400740/bf2fc6e2-5a9d-11e6-80f9-ad174ba82434.png)

**Comment by sg-s** [comment]
happened to be for a bit, but then went away on its own

**Comment by boramalper** [comment]
It happens to me as well (I'm on Ubuntu), although it goes away on its own as @sg-s said.

I have no idea why it's happening: maybe it's a bug in [the programs we're calling](https://github.com/boramalper/himawaripy/blob/master/himawaripy/utils.py)?

**Comment by lachlandcp** [comment]
I think it's something to do with dates & timezones.

For instance, I'm in New Zealand (UTC+12), and currently it tries to request the tile `2016/08/06/003000`, where as the latest tiles avaliable are for `2016/08/05/223000`.

It's trying to request the tiles from tomorrow (or something like that).

**Comment by hche608** [comment]
@imnofox you are correct, fixed the problem by deleting
`line 36        offset_tmp = offset_tmp + timedelta(hours=offset)`

**Comment by lachlandcp** [comment]
Isn't deleting that line just the same as disabling auto_offset in config.py?

**Comment by boramalper** [comment]
@imnofox is right. The issue is still unsolved so I reopened it. I'll work on a fix asap.

Thanks everyone for figuring it out. Really really nice catch!

**Comment by hche608** [comment]
@boramalper is it a logic issue? I am in New Zealand,  which is 2 hours beyond the himawaripy time, but the code requests IMG base on NZ time which is a future time. I have check the code offset hour is correct, which is 2 hours, 

|  | Local time | himawaripy time | Local time |
| --- | --- | --- | --- |
|  | 6PM | 9PM | 11PM |
| Offset Hours | -3 | 0 | 2 |

11PM - 2hours = 6PM - -3hours = 9PM

`line 36        offset_tmp = offset_tmp - timedelta(hours=offset)`

**Comment by Detavern** [comment]
It's an issue of himawari8 website itself, sometimes it just didn't have any images. 
You can have a try here:
[himawari8](http://himawari8.nict.go.jp/himawari8-image.htm?sI=D531106&sCl=false&sClC=ffff00&sS=4&sNx=1&sNy=0&sL=-167&sT=-534&wW=2497&wH=861&sD=1471056000000)
[Relevant image url](http://himawari8-dl.nict.go.jp/himawari8/img/D531106/1d/550/2016/08/13/024000_0_0.png)
I'm not sure if it's same(black background with "No Image" on it) for you

how to solve it:
if you got a "No Image" response
try to request a more earlier image
20 minutes delayed is near-realtime too

**Comment by Detavern** [comment]
And I have another question about why we need time zone offset ...
you know that himawari8 is a geosynchronous orbit satellite.
it can't capture image of earth on the other side ...

**Comment by sg-s** [comment]
@Detavern because if you didn't, and lived in the Western Hemisphere, with no offset, you'd only see a dark picture during the daytime hours (when you're awake and using your computer)

**Comment by Detavern** [comment]
@sg-s but.. even you awake, looking at the Australia on image with sunshine, you may suddenly realize that the Western Hemisphere is still in dark XD
maybe we need another satellite

**Comment by sg-s** [comment]
yeah, this is a workaround because we don't have access to an equivalent satellite for the western hemisphere. actually, if you didn't want an offset, you need a geosynchronous satellite for every longitude

**Comment by boramalper** [comment]
Hello,

as I've said in #82, this was due to a problem in time logic of himawaripy.

Can you please make a clean installation of v2 (https://github.com/boramalper/himawaripy/tree/v2) and let me know if it fixes your problem?

Thanks!

**Comment by boramalper** [comment]
I assume the problem has been solved, let me know if it still persist. Thanks!
