### ISSUE TITLE
No such key 'draw-background' on Cinnamon

### ISSUE THREAD

**Issue by RyuzakiKK** [boramalper/himawaripy#7]
I have Arch Linux with Cinnamon and I get this error:

```
./himawaripy.py
Updating...
Latest version: 2016/02/04/18:50:00 GMT

Downloading tiles: 16/16 completed
Downloaded

No such key 'draw-background'
Done!
```

**Comment by Chrismarsh** [comment]
Same issue with Gnome 3 and Fedora 22. I just commended out that line and it seems to work...

**Comment by RyuzakiKK** [comment]
Same here. Commenting the line:
`# call(["gsettings", "set", "org.gnome.desktop.background", "draw-background", "false"])`
It works and the wallpaper is set correctly.

**Comment by Chrismarsh** [comment]
I assume it's addressing this bug, which looks like it might be unity-specific?
http://askubuntu.com/a/418521

**Comment by boramalper** [comment]
Should be fine now. :) https://github.com/boramalper/himawaripy/commit/d33338f30fcff2421250176748e5205620a23655

**Comment by RyuzakiKK** [comment]
@boramalper ok, now it works.

**Comment by Chrismarsh** [comment]
Works here.
