### ISSUE TITLE
I did a tiny change made new coming pic named by date.  i wonder how to store a whole day's pic and make backgroud replay?

### ISSUE THREAD

**Issue by indescribable** [boramalper/himawaripy#75]
I did a tiny change made new coming pic named by date.  i wonder how to store a whole day's pic and make backgroud replay?

himawaripy/confif.py
output_file = os.path.join(appdirs.user_cache_dir(appname="himawaripy",
                                                  appauthor=False),
                           time.ctime()  )
                            ^^^^^^^^^^^
this will store everyday's pic....and will take huge space....but,we just need one days loop....

**Comment by indescribable** [comment]
i donno if its properly write here.this is not some kindof issue.more like a new function request...
maybe someone can tell me ?

**Comment by boramalper** [comment]
himawaripy is to fetch (almost) real-time picture of Earth, not to cycle old images of it, although that's also understandable.

You can save the photos as you said in a directory and then loop over them to change wallpaper in every 10 minutes. KDE supports this out-of-the-box I think, but you can always write a script.

Closing the issue as it's not relevant to himawaripy.
