### ISSUE TITLE
Time offset confusion

### ISSUE THREAD

**Issue by squilter** [boramalper/himawaripy#85]
I wanted real-time pictures. I kept getting them at some other time. So I went into the config file, and it said "using the default values, script will put the realtime picture of Earth". But it clearly wasn't. So then I changed `True` to `False` and then it was correct. Either this comment is misleading, or something else is wrong.

**Comment by boramalper** [comment]
Hello,

can you please make a clean installation of v2 (https://github.com/boramalper/himawaripy/tree/v2) and let me know if it fixes your problem?

Thanks!

**Comment by squilter** [comment]
It's great, thanks!

**Comment by boramalper** [comment]
You're welcome! :)
