### ISSUE TITLE
Checking OS X compatibility of v2

### ISSUE THREAD

**Issue by boramalper** [boramalper/himawaripy#86]
Hello,

can someone who is using himawaripy on OS X (or macOS, whatever) check whether [v2](https://github.com/boramalper/himawaripy/tree/v2) is working smoothly on OS X?

Battery saving option won't work, I am aware of that.

/CC @jcmiller11

**Comment by Cabalist** [comment]
Just tried on a 10.10 machine and it is working great.  Anything in particular you'd like me to bang on?

**Comment by boramalper** [comment]
Sorry for such a belated answer (excuse me for university applications); thanks!
