### ISSUE TITLE
Add Europe centered view

### ISSUE THREAD

**Issue by Daniel-at-github** [boramalper/himawaripy#89]
If anyone want to other views of the world, here is the data for Europe near real time image satellite:
- URL: http://oiswww.eumetsat.org/IPPS/html/latestImages/EUMETSAT_MSG_RGBNatColour_LowResolution.jpg
- Update time: 1h

Source: http://oiswww.eumetsat.org/IPPS/html/latestImages.html

**Comment by boramalper** [comment]
Hello @Daniel-at-github,

many people would like a _better_ version of the image such as:

* higher resolution (the "smallest" resolution himawaripy provides is 2200x2200)
* cleaner image without the white dots and outlines of the countries. I think we can strip the bottom-line ourselves so it should be fine for now.

Sorry for belated reply, I was applying to universities. I would be glad to add another satellite.=)

**Comment by Daniel-at-github** [comment]
@boramalper I'm afraid that the url for [EUMETSAT_MSG_RGBNatColour_LowResolution.jpg](http://oiswww.eumetsat.org/IPPS/html/latestImages/EUMETSAT_MSG_RGBNatColour_LowResolution.jpg) is the best they gave for free. I looked for a better one with no luck.

**Comment by boramalper** [comment]
Then I am afraid it is better not to add it.

Thanks for the suggestion though, I appreciate that.=)
