### ISSUE TITLE
OSX Service Already Loaded

### ISSUE THREAD

**Issue by dynnamic** [boramalper/himawaripy#91]
I think I've followed the directions, yet I'm getting the message that says the following.

/Users/James/Library/LaunchAgents/org.boramalper.himawaripy.plist: service already loaded

How do I get the background to start?

**Comment by boramalper** [comment]
Apologies that I couldn't help (as I was busy, and I am not familiar with macOS). I am closing the issue but feel free to comment if the issue persists.
