### ISSUE TITLE
New implementation with python2.7

### ISSUE THREAD

**Issue by littleningmeng** [boramalper/himawaripy#93]
Hi, boramalper
Thanks to your great job, I re-implemented some features of himawaripy on Python2.7 whitch especially for Windows user.
My repo is https://github.com/littleningmeng/blueearth.git
And here is the release version https://github.com/littleningmeng/blueearth/releases

**Comment by boramalper** [comment]
Hello, thanks for the heads up! himawaripy is strictly GNU/Linux and macOS only (as there is a Windows version which himawaripy was modeled after), but I can suggest you to create an installable package of blueearth for Windows. =)

Thanks!
