### ISSUE TITLE
support Ubuntu kylin  17.10  defaluts destop ukui  

### ISSUE THREAD

**Issue by ghost** [boramalper/himawaripy#96]
Ubuntu kylin  17.10  defaluts destop is ukui 
can you change something to surpport  ukui  desktop.

i try to find  how to do it, but  has not found yet.

**Comment by boramalper** [comment]
Hey @lichengshuang! When you run himawaripy on Ubuntu 17.10, what error/output do you exactly get?

**Comment by ghost** [comment]
now i use ubutnu 18.04  it's run ok

**Comment by boramalper** [comment]
Feel free to reopen the issue if you need. =)
