### ISSUE TITLE
GLib-Gio-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

### ISSUE THREAD

**Issue by Partinax** [boramalper/himawaripy#97]
So this was happening to me for a while, and I eventually found out it has to do with my Anaconda python install.

Anyone who has anaconda installed will find that their gsettings command now references the anaconda directory: /home/matt/anaconda2/bin/gsettings

And for whatever reason, this gsettings can not save settings for other applications, and this error pops up when you run the scripts: "GLib-Gio-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications." And the wallpaper does not update.

To fix this, I went into the utilsy.py file in himawaripy-master/himawaripy and changed all the references to gsettings to instead reference the specific system gsettings: usr/bin/gsettings

This fixed the problem that was introduced by the anaconda install. Perhaps the devs should think about making this a permanent update to the script.

**Comment by Partinax** [comment]
However, while running the script manually works, if I try to run it using either crontab or systemd, the new image is downloaded, and the old one removed, but the wallpaper is not updated. So the wallpaper just becomes a black screen as it tries to reference the now deleted image.

**Comment by djmbritt** [comment]
You can fix this by changing it in .bashrc.
Change: `export PATH="/home/djmbritt/anaconda3/bin:$PATH"`
To: `export PATH="$PATH:/home/djmbritt/anaconda3/bin"`

**Comment by boramalper** [comment]
> However, while running the script manually works, if I try to run it using either crontab or systemd, the new image is downloaded, and the old one removed, but the wallpaper is not updated. So the wallpaper just becomes a black screen as it tries to reference the now deleted image.

@Partinax The new version that I have (just!) released solves the problem. Can you please try it yourself and let me know if the issue persists?
